###
### --- Can be loaded by args
### ---   If loaded y args are prior
###

# folder with training data
folder_data_path: "/home/juan/Documentos/AAUniversidad/tesis/BrakeBalls/data/training_data"

# folder for results
folder_result_path: "/home/juan/Documentos/AAUniversidad/tesis/BrakeBalls/model_training/test"

# hot much of the total data use for train (testing pourpuse)
data_percentage_to_use: 0.001

# how much of the data use for training and the rest to eval
train_percentage_split: 0.8

# batch_size
batch_size: 3

# size of the image input
image_size: 256

# define if use cuda or not
useCuda: True

# epochs
epochs: 5

# learning rate for training
learning_rate: 0.001

# if running in colab
colab: False
